apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsidXNlcm5hbWUiOiJSYXNwdXRpbjIiLCJwYXNzd29yZCI6ImdocF9sNkRlbFBSaDVZWWcyMnI1ZURZbkI3Zk5QMDBTNnQyMERFRVEiLCJhdXRoIjoiVW1GemNIVjBhVzR5T21kb2NGOXNOa1JsYkZCU2FEVlpXV2N5TW5JMVpVUlpia0kzWms1UU1EQlROblF5TUVSRlJWRT0ifX19
