name: CI/CD

on:
  push:
    branches: [main]
    paths-ignore:
      - 'backend.yaml'
      - 'frontend.yaml'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Add ARM emulation support
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Add the multi-architecture builder
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Combines build and push for backend into one step targeting ARM64
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./src/backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/rasputin2/backend:${{ github.sha }}

      # Combines build and push for frontend into one step targeting ARM64
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./src/frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/rasputin2/frontend:${{ github.sha }}

      - name: Update Kubernetes manifests
        run: |
          sed -i "s|image: ghcr.io/rasputin2/backend:.*|image: ghcr.io/rasputin2/backend:${GITHUB_SHA}|" backend.yaml

          sed -i "s|image: ghcr.io/rasputin2/frontend:.*|image: ghcr.io/rasputin2/frontend:${GITHUB_SHA}|" frontend.yaml

      - name: Commit updated manifests
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add backend.yaml frontend.yaml

          git commit -m "Update image tags to ${GITHUB_SHA}" || exit 0

          git push